# Generated by Django 4.2.7 on 2025-05-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_remove_libro_disponible_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nacionalidad',
            field=models.CharField(choices=[('AR', 'Argentina'), ('BO', 'Bolivia'), ('BR', 'Brasil'), ('CL', 'Chile'), ('CO', 'Colombia'), ('EC', 'Ecuador'), ('ES', 'España'), ('MX', 'México'), ('PE', 'Perú'), ('PY', 'Paraguay'), ('UY', 'Uruguay'), ('VE', 'Venezuela'), ('OT', 'Otra')], default='OT', max_length=2),
        ),
    ]
